[tool.poetry]
name = "mbta-performance"
version = "0.1.0"
description = "Processing of static MBTA performance data"
authors = ["TransitMatters Labs Team"]
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
requests = "^2.32.3"
boto3 = "^1.35.5"
pandas = "^2.2.2"
datadog_lambda = "6.98.0"
pyarrow = "^15.0.2"
mbta-gtfs-sqlite = "^1.1.1"

[tool.poetry.dev-dependencies]
chalice = "^1.31.2"
flake8 = "^7.1.1"
black = "^24.8.0"
pytest = "~8.3.2"

[tool.black]
line-length = 120
target-version = ['py312']

[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"
